import type { DaySummary, WeekData } from '@/types/dashboard';

const MOCK_DAYS: readonly DaySummary[] = [
  {
    dayLabel: 'Monday',
    dayShort: 'Mon',
    date: 'Mar 15',
    hasActivity: true,
    activityType: 'Run',
    activityName: 'Easy Recovery Run',
    distanceKm: 6.1,
    durationSec: 2196,
    paceSecPerKm: 360,
    averageHeartRate: 138,
    elevationGainM: 32,
    calories: 445,
    effort: 48,
  },
  {
    dayLabel: 'Tuesday',
    dayShort: 'Tue',
    date: 'Mar 16',
    hasActivity: true,
    activityType: 'Run',
    activityName: 'Tempo Intervals',
    distanceKm: 8.4,
    durationSec: 2520,
    paceSecPerKm: 300,
    averageHeartRate: 162,
    elevationGainM: 55,
    calories: 620,
    effort: 112,
  },
  {
    dayLabel: 'Wednesday',
    dayShort: 'Wed',
    date: 'Mar 17',
    hasActivity: false,
  },
  {
    dayLabel: 'Thursday',
    dayShort: 'Thu',
    date: 'Mar 18',
    hasActivity: true,
    activityType: 'Run',
    activityName: 'Hill Repeats',
    distanceKm: 7.2,
    durationSec: 2340,
    paceSecPerKm: 325,
    averageHeartRate: 158,
    elevationGainM: 185,
    calories: 580,
    effort: 95,
  },
  {
    dayLabel: 'Friday',
    dayShort: 'Fri',
    date: 'Mar 19',
    hasActivity: true,
    activityType: 'Run',
    activityName: 'Easy Shakeout',
    distanceKm: 5.3,
    durationSec: 1908,
    paceSecPerKm: 360,
    averageHeartRate: 135,
    elevationGainM: 22,
    calories: 385,
    effort: 38,
  },
  {
    dayLabel: 'Saturday',
    dayShort: 'Sat',
    date: 'Mar 20',
    hasActivity: true,
    activityType: 'Run',
    activityName: 'Long Run',
    distanceKm: 15.3,
    durationSec: 4590,
    paceSecPerKm: 300,
    averageHeartRate: 150,
    elevationGainM: 118,
    calories: 1120,
    effort: 142,
  },
  {
    dayLabel: 'Sunday',
    dayShort: 'Sun',
    date: 'Mar 21',
    hasActivity: false,
  },
];

export const MOCK_WEEK: WeekData = {
  weekLabel: 'Week of Mar 15',
  dateRange: 'Mon Mar 15 -- Sun Mar 21, 2026',
  days: MOCK_DAYS,
  totals: {
    activities: MOCK_DAYS.filter((d) => d.hasActivity).length,
    distanceKm: MOCK_DAYS.reduce((sum, d) => sum + (d.distanceKm ?? 0), 0),
    durationSec: MOCK_DAYS.reduce((sum, d) => sum + (d.durationSec ?? 0), 0),
    elevationGainM: MOCK_DAYS.reduce((sum, d) => sum + (d.elevationGainM ?? 0), 0),
    calories: MOCK_DAYS.reduce((sum, d) => sum + (d.calories ?? 0), 0),
    effort: MOCK_DAYS.reduce((sum, d) => sum + (d.effort ?? 0), 0),
  },
  aiSummary:
    'Consistent week with good volume distribution. Distance up 8% vs last week at similar ' +
    'heart rate -- aerobic fitness is improving. Tuesday tempo and Thursday hills provided solid ' +
    'stimulus. Saturday long run was well-paced with a negative split. ' +
    'Consider adding one interval session next week to sharpen speed.',
};
